### ISSUE TITLE
Blinky not part of the standard fusesoc library?

### ISSUE THREAD

**Issue by tomverbeure** [fusesoc/blinky#27]
According to the README:

> This project is available in the FuseSoC base library, so if you have FuseSoC installed, you likely already have this project as well.

However, when I ran `fusesoc list-cores`, `blinky` wasn't included.  I also couldn't find it here: https://github.com/fusesoc/fusesoc-cores.

Is the README wrong or hasn't it been included in the standard library just yet?

Tom

**Comment by olofk** [comment]
Well, that's clearly a lie. I'll add it.

**Comment by olofk** [comment]
[Done](https://github.com/fusesoc/fusesoc-cores/commit/96bba8dde422c4d674807c7892868db7ac5a5e5f). Thanks for picking this up
