### ISSUE TITLE
Error on core-info 

### ISSUE THREAD

**Issue by euripedesrocha** [fusesoc/blinky#9]
When experimenting with the core before add another board I got the folowing error:

Unknown item 'filesets_append in section Target'

Fusesoc version: 1.9.2

**Comment by olofk** [comment]
Oh, you're right. Sorry about that. There was actually two issues. filesets_append was not supported in 1.9.2 and also, 1.9.2 stopped parsing when it encountered tags that it didn't know about. I decided to release a new version to fix these issues, so please try again with the newly released FuseSoC 1.9.3 and let me know if that works better

**Comment by euripedesrocha** [comment]
The new version fixed the issue. Thanks!
